create table if not exists public.quiz_comments (
  id bigint generated by default as identity primary key,
  quiz_name text not null check (char_length(quiz_name) between 2 and 30),
  parent_id bigint references public.quiz_comments(id) on delete cascade,
  visitor_id text not null check (char_length(visitor_id) between 8 and 80),
  nickname text not null default '匿名访客' check (char_length(nickname) between 1 and 20),
  content text not null check (char_length(content) between 2 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.test_reactions (
  quiz_name text not null check (char_length(quiz_name) between 2 and 30),
  visitor_id text not null check (char_length(visitor_id) between 8 and 80),
  reaction text not null check (reaction in ('like', 'favorite')),
  created_at timestamptz not null default now(),
  primary key (quiz_name, visitor_id, reaction)
);

create table if not exists public.comment_reactions (
  comment_id bigint not null references public.quiz_comments(id) on delete cascade,
  visitor_id text not null check (char_length(visitor_id) between 8 and 80),
  reaction text not null check (reaction in ('like', 'favorite')),
  created_at timestamptz not null default now(),
  primary key (comment_id, visitor_id, reaction)
);

create index if not exists quiz_comments_quiz_created_idx
  on public.quiz_comments (quiz_name, created_at desc);
create index if not exists comment_reactions_comment_idx
  on public.comment_reactions (comment_id);

alter table public.quiz_comments enable row level security;
alter table public.test_reactions enable row level security;
alter table public.comment_reactions enable row level security;

revoke all on table public.quiz_comments from anon, authenticated;
revoke all on table public.test_reactions from anon, authenticated;
revoke all on table public.comment_reactions from anon, authenticated;

grant select, insert, update, delete on table public.quiz_comments, public.test_reactions, public.comment_reactions to service_role;
grant usage, select on all sequences in schema public to service_role;
