create table if not exists public.test_suggestions (
  id bigint generated by default as identity primary key,
  idea text not null check (char_length(idea) between 2 and 120),
  target text not null check (char_length(target) between 2 and 80),
  note text not null default '' check (char_length(note) <= 360),
  created_at timestamptz not null default now()
);

create table if not exists public.private_feedback (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 2 and 600),
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.test_suggestions enable row level security;
alter table public.private_feedback enable row level security;
alter table public.site_content enable row level security;

revoke all on table public.test_suggestions from anon, authenticated;
revoke all on table public.private_feedback from anon, authenticated;
revoke all on table public.site_content from anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.test_suggestions, public.private_feedback, public.site_content to service_role;
grant usage, select on all sequences in schema public to service_role;
