create table if not exists public.reaction_scores (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 16),
  score_ms integer not null check (score_ms between 100 and 60000),
  created_at timestamptz not null default now()
);

create index if not exists reaction_scores_score_created_idx
  on public.reaction_scores (score_ms asc, created_at asc);

alter table public.reaction_scores enable row level security;

revoke all on table public.reaction_scores from anon, authenticated;
grant select, insert on table public.reaction_scores to service_role;
grant usage, select on sequence public.reaction_scores_id_seq to service_role;
